[platformio]
default_envs = neomind_v1

[env:neomind_v1]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 115200
upload_speed = 115200
build_flags =
    -D NEOMIND_V1
    -D NEOMIND_HOST_PROTOCOL
